### ISSUE TITLE
Day page does not work when refreshing

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Calendar#22]
### Steps to reproduce

1. Start Calendar `develop` branch
2. Start Launcher `develop`
3. Start SignIn `develop`
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/launcher`
6. Sign in as admin user
7. Click on the "Calendar" icon.
8. Click on a single day, the URL changes to: `http://localhost:8080/Calendar?view=agendaDay&day=2017-02-07`
9. Press F5 to reload the page

### Expected result

The page should correctly reload with the day view.

### Actual result

When you reload the page at this point, there is a 404 error page.

Notice: The error only appears when clicking on the Calendar icon in step 7. When you click on the Calendar menu link instead, it works OK.

**Comment by un-tone** [comment]
Closing as done
